server:
  port: 8082

spring:
  profiles:
    active: minikube
  application:
    name: product

product:
  image:
    directory: ${user.dir}\microservices\product\src\main\resources\static\product\img