version: '3.8'

services:

  registry:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    container_name: registry
    ports:
      - "8761:8761"
    volumes:
      - ../microservices/registry:/app
    working_dir: /app
    command: "mvn spring-boot:run"

  gateway:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    container_name: gateway
    depends_on:
      - product
    ports:
      - "8888:8888"
    volumes:
      - ../microservices/gateway:/app
    working_dir: /app
    command: "mvn spring-boot:run"

  product:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    container_name: product
    depends_on:
      - database
    ports:
      - "8082:8082"
    volumes:
      - ../microservices/product:/app
    working_dir: /app
    command: "mvn spring-boot:run"

  database:
    image: postgres:16.1-alpine
    container_name: database
    depends_on:
      - registry
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: poc-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  angular:
    image: nginx:alpine
    container_name: angular
    ports:
      - "80:80"
    volumes:
      - ../frontend/dist/frontend/browser:/usr/share/nginx/html

volumes:
  postgres_data: