version: '3.8'

services:

  registry:
    build:
      context: ../microservices/registry
      dockerfile: ./docker/Dockerfile
    image: poc-registry:0.0.1
    container_name: registry
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ../microservices/gateway
      dockerfile: ./docker/Dockerfile
    image: poc-gateway:0.0.1
    container_name: gateway
    depends_on:
      - product
    ports:
      - "8888:8888"

  product:
    build:
      context: ../microservices/product
      dockerfile: ./docker/Dockerfile
    image: poc-product:0.0.1
    container_name: product
    depends_on:
      - database
    ports:
      - "8082:8082"

  database:
    image: postgres:16.1-alpine
    container_name: database
    depends_on:
      - registry
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: poc-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: