server:
  port: 8888

spring:
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/product/**
        - id: product-images
          uri: lb://PRODUCT
          predicates:
            - Path=/product/img/**

