server:
  port: 8888

spring:
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: product
            uri: lb://PRODUCT
            predicates:
              - Path=/api/product/**